export const services = [
  { name: 'Bookkeeping and Accounting', 
    titleFeatures: 'Managing Director',
    image: './images/sajad.jpg',
   },
  { name: 'Administrative Support and Executive Assistants', 
    title: 'Director' ,
    image: './images/uzair.jpg',
  },
  { name: 'Manpower Supply and Recruitment',
    features: 'Operations Director',
    image: './images/riyaz1.jpeg',
   },
   { name: 'Manpower Supply and Recruitment',
    title: 'Operations Director',
    image: './images/riyaz1.jpeg',
   },
    { name: 'IT Services and Support',
        title: 'Operations Director',
        image: './images/riyaz1.jpeg',
     },
  
];